import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from 'react-hot-toast';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: '#1A1A2E',
              color: '#fff',
              fontSize: '13px',
              borderRadius: '16px',
              border: '1px solid rgba(255,255,255,0.1)',
              padding: '16px 20px',
              boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.2), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
            },
            success: {
              iconTheme: {
                primary: '#1D9E75',
                secondary: '#fff',
              },
              style: {
                background: '#1A1A2E',
                color: '#fff',
                borderLeft: '4px solid #1D9E75'
              }
            },
            error: {
              iconTheme: {
                primary: '#E24B4A',
                secondary: '#fff',
              },
              style: {
                background: '#1A1A2E',
                color: '#fff',
                borderLeft: '4px solid #E24B4A'
              }
            },
          }}
        />
      </body>
    </html>
  );
}
